# Generated by Django 4.0.2 on 2022-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.TextField()),
                ('username', models.CharField(max_length=100)),
                ('search_result', models.TextField(default='pgitcmhjmgtohjptgtcn')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
